# Generated by Django 4.2.4 on 2023-10-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_authgroup_delete_authgrouppermissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_title", models.CharField(blank=True, max_length=500, null=True)),
                ("user_title_embedding", models.TextField(blank=True, null=True)),
                ("user_song_id_lst", models.TextField(blank=True, null=True)),
                ("user_tag_lst", models.TextField(blank=True, null=True)),
                ("user_updt", models.CharField(blank=True, max_length=100, null=True)),
                ("user_like_cnt", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_log",
                "managed": False,
            },
        ),
    ]
